### ISSUE TITLE
question: sample with a role being passed to grpc service.

### ISSUE THREAD

**Issue by arjunkrishna** [javiercn/BlazorGrpcAuth#2]
Hello,
   This code does not seem to handle roles. Do you know how to pass a role claim to grpc service?
 on client's side I tried adding but it does not send the role claim to grpc service even when userInfo shows the role in chrome dev tools.

builder.Services.AddApiAuthorization(options =>
            {
                options.UserOptions.RoleClaim = "role";                
            });

I thought github had a discussion section for a repo. so I am using this... so sorry.

**Comment by JeepNL** [comment]
I've used this snippet from Javier 

    endpoints
        .MapGrpcService<GreeterService>()
        .RequireAuthorization(new AuthorizeAttribute { Roles = "Administrator"})
        .EnableGrpcWeb();

in this GitHub Repository: https://github.com/JeepNL/Blazor-WASM-Identity-gRPC

**Comment by arjunkrishna** [comment]
Thank you. I'll check that repository as well.
Regards,
Arjun

**Comment by arjunkrishna** [comment]
Thank you. I finally got around trying your recommendation. It worked. Interesting way of associating an authorize requirement.

The other repo was really helpful.

**Comment by JeepNL** [comment]
@arjunkrishna FYI: Javier gave me a tip to solve a bug in my code for additional claims. I don't know if you use that as well, but here's the change: https://github.com/JeepNL/Blazor-WASM-Identity-gRPC/commit/7fa53fb695a6df6735f32f736e9abf89a84837be

**Comment by arjunkrishna** [comment]
Thank you @JeepNL. I just incorporated it. I did glance at your profile service code... at present I am not there yet, but will keep an eye on it. Today will try to read code about how state management works in blazor wasm and best way to persist it, locally and on server and sync them appropriately.

Thank you again.

**Comment by JeepNL** [comment]
You're welcome Arjun!

**Comment by arjunkrishna** [comment]
Hello again @JeepNL, 

I started looking at this today after a long time.  I noticed that AppClaimsPrincipalFactory.GenerateClaimsAsync method is called three times while the login process. Do you know why that is?
regards,
Arjun

**Comment by JeepNL** [comment]
I'm sorry, I do not know why that is. Perhaps a good question for the ASP.NET Team / Javier.
